const {
  MODE: ENVIRONMENT,
  NODE_ENV: NODE_ENV,
  DEV: DEV,
  PROD: PROD,
  VITE_POLYGON_API_KEY: POLYGON_API_KEY,
} = import.meta.env;

export { ENVIRONMENT, NODE_ENV, DEV, PROD, POLYGON_API_KEY };
